echo "i dictionary_bTList output/output
E tests/initial_tests/test1 output/output1
E tests/initial_tests/test2 output/output2
E tests/initial_tests/test3 output/output3
E tests/initial_tests/test4 output/output4
E tests/initial_tests/test5 output/output5
E test1 output/output6
E test1 output/output7
E test2 output/output8
E WindowScript output/output9
E test1 output/output10
E test2 output/output11
E test1 output/output6
E test1 output/output7
E test2 output/output8
E WindowScript output/output9
E test1 output/output10
E test2 output/output11
E tests/initial_tests/test1 output/output1
E tests/initial_tests/test2 output/output2
E tests/initial_tests/test3 output/output3
E tests/initial_tests/test4 output/output4
E tests/initial_tests/test5 output/output5
E test1 output/output6
E test1 output/output7
E test2 output/output8
E WindowScript output/output9
E test1 output/output10
E test2 output/output11
E test1 output/output6
E test1 output/output7
E test2 output/output8
E WindowScript output/output9
E test1 output/output10
E test2 output/output11
E tests/initial_tests/test1 output/output1
E tests/initial_tests/test2 output/output2
E tests/initial_tests/test3 output/output3
E tests/initial_tests/test4 output/output4
E tests/initial_tests/test5 output/output5
E test1 output/output6
E test1 output/output7
E test2 output/output8
E WindowScript output/output9
E test1 output/output10
E test2 output/output11
E test1 output/output6
E test1 output/output7
E test2 output/output8
E WindowScript output/output9
E test1 output/output10
E test2 output/output11
E tests/initial_tests/test1 output/output1
E tests/initial_tests/test2 output/output2
E tests/initial_tests/test3 output/output3
E tests/initial_tests/test4 output/output4
E tests/initial_tests/test5 output/output5
E test1 output/output6
E test1 output/output7
E test2 output/output8
E WindowScript output/output9
E test1 output/output10
E test2 output/output11
E test1 output/output6
E test1 output/output7
E test2 output/output8
E WindowScript output/output9
E test1 output/output10
E test2 output/output11
E tests/initial_tests/test1 output/output1
E tests/initial_tests/test2 output/output2
E tests/initial_tests/test3 output/output3
E tests/initial_tests/test4 output/output4
E tests/initial_tests/test5 output/output5
E test1 output/output6
E test1 output/output7
E test2 output/output8
E WindowScript output/output9
E test1 output/output10
E test2 output/output11
E test1 output/output6
E test1 output/output7
E test2 output/output8
E WindowScript output/output9
E test1 output/output10
E test2 output/output11
E tests/initial_tests/test1 output/output1
E tests/initial_tests/test2 output/output2
E tests/initial_tests/test3 output/output3
E tests/initial_tests/test4 output/output4
E tests/initial_tests/test5 output/output5
E test1 output/output6
E test1 output/output7
E test2 output/output8
E WindowScript output/output9
E test1 output/output10
E test2 output/output11
E test1 output/output6
E test1 output/output7
E test2 output/output8
E WindowScript output/output9
E test1 output/output10
E test2 output/output11
E tests/initial_tests/test1 output/output1
E tests/initial_tests/test2 output/output2
E tests/initial_tests/test3 output/output3
E tests/initial_tests/test4 output/output4
E tests/initial_tests/test5 output/output5
E test1 output/output6
E test1 output/output7
E test2 output/output8
E WindowScript output/output9
E test1 output/output10
E test2 output/output11
E test1 output/output6
E test1 output/output7
E test2 output/output8
E WindowScript output/output9
E test1 output/output10
E test2 output/output11
E tests/initial_tests/test1 output/output1
E tests/initial_tests/test2 output/output2
E tests/initial_tests/test3 output/output3
E tests/initial_tests/test4 output/output4
E tests/initial_tests/test5 output/output5
E test1 output/output6
E test1 output/output7
E test2 output/output8
E WindowScript output/output9
E test1 output/output10
E test2 output/output11
E test1 output/output6
E test1 output/output7
E test2 output/output8
E WindowScript output/output9
E test1 output/output10
E test2 output/output11
w
"| ./server_coarse file
